name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: github-pages
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}]
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: which git
    - name: Setup Git
      env:
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
        MY_NAME: ${{ secrets.MY_NAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "${MY_EMAIL}"
        git config --global user.name "${MY_NAME}"
        git config --global credential.helper store
        echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
    - run: npm i
    - run: npm ci
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run deploy
